### ISSUE TITLE
implementing spectrum arithmetic

### ISSUE THREAD

**Issue by perrygreenfield** [spacetelescope/specview#1]
Generated from [trello feature](https://trello.com/c/SbgldpUq).

I'm proposing a simple editing interface to take place on the spectral object pane in the viewer window. 

This presumes that all existing objects have a unique name that can be used in an expression (and even if some of these objects are subsequently deleted from the viewer pane, any expressions that use them imply that these objects still are available for reference (i.e., they aren't garbage collected) [that makes me wonder if there shouldn't be an optional dialog for available objects for selection to put in the viewer].

So I envision that the viewer pane has a right button drop down that has a "add expression" option. Once chosen, an editing mode begins (could be a dialog, or just editing a line in the pane it self--I'd argue whatever is easiest to implement now). Normally I'd say we allow a free form editing, and if object are referred to that don't exist, or the syntax of the expression is invalid, or uses functional forms not available or not found, an error is raised. Preferably the expression text is still available for further editing (don't force the user to re-enter it all over again) so they can attempt to correct it. 

Perhaps more functionality can be added to allow someone to choose an object from existing objects to include in the expression, but simplicity, I would say just the string name for the object to make it simpler in the initial implementation.

One question is does the new expression itself get a name that can be referred to. It would be nice so it can also be referred to. By default perhaps expr1, expr2, etc. But if the expression is an assignment, then the identifier on the left becomes the name of the object created, e.g., 

scaled_spectrum = 1.34 \* myobs

Permitted operations and functions

+,-,/,\* (*\* only seems to make sense for scalars, but maybe there is a use case for that)
z(spectrum, redshift)

Implementation question. Use of eval is the simplest solution (perhaps the initial one), but it doesn't provide restricted usage features (The user can use any function they want; maybe that's good). I suspect there's a tool out there that can do that sort of thing for us, but again, the simplest initial case is eval.

Use of Quantities. I think that is implicitly permitted but may need a little thought.

**Comment by hcferguson** [comment]
Glue allows you define additional �columns� for a data set that can hold
the output of a calculation and keep it attached to one of the original data
sets. This is pretty handy.

x[�result�] = x[�observed�] - model # for example, if x is a astropy table (or recarray? Not sure�).

Regarding operations (from splot manual):
Arithmetic +,-,/,*
Exponentiation, log (base e and w0)
Square (for convenience0
Absolute value

-Harry

Henry C. Ferguson
Space Telescope Science Institute
email: ferguson@stsci.edu
phone: (410) 338-5098
fax: (410) 338-4976

**Comment by perrygreenfield** [comment]
Certainly these are all good things. I'd add wavelength modifiers as well (z being one example, but other simple transformations such as simple offset to correspond to the alignment needs of Jeff).

As for Glue data set columns, we should see if that works well outside of glue. That should have some thought. Perhaps not immediately implemented, but something to keep in mind.

**Comment by SaOgaz** [comment]
Closing, repository being archived.
