### ISSUE TITLE
Region selection

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/specview#11]
Generated from [trello feature](https://trello.com/c/l82aagTt).

**Comment by nmearl** [comment]
The way this is implemented now is that the ROI selector implicitly returns information about _both_ the wavelength and the flux. This is such that an ROI selector can be agnostic (i.e. the two axes really don't even matter). Thus, we could use them for e.g. selection regions on images.

If no one has a compelling reason for a "range" selector, as opposed to a region selector, I think we can close this.
