### ISSUE TITLE
Data sets for testing

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specview#16]
Opening an issue for notes about data and data sets.

**Comment by hcferguson** [comment]
Sent requests out to Kassin, Valenti, Beck and Hines.

**Comment by stscieisenhamer** [comment]
Sent email about, but data can be stored at

/astro/3/jwst-da-sprint-201502

**Comment by hcferguson** [comment]
spec1d.3100.069.31016909.fits has one-d spectra in fits tables. 
In [2]: hdu = fits.open('spec1d.3100.069.31016909.fits')
In [3]: s = hdu[1].data
In [4]: wave,flux = s['LAMBDA'],s['SPEC']

**Comment by stscieisenhamer** [comment]
Added README.rst to the folder to document any information about the data included.

**Comment by stscieisenhamer** [comment]
S.Kassin also suggests that the standard stars in
/grp/hst/cdbs/calspec

**Comment by stscieisenhamer** [comment]
Under the fixed folder, there is a 'califa' folder that has a complete CALIFA dataset, where the spectra are split out into 1D images, with a header WCS for wavelength defined which can be used with the astropy.wcs object.  Choose some of the middle range spectra for interesting features, such as the 2000-range.
