### ISSUE TITLE
Default data model

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/specview#3]
Suggest that it be astropy v1.0 NDData.

However, for larger collections, is there some standard we can go with? I know glue has the Data Collection, but is there something else.

**Comment by stscieisenhamer** [comment]
From morning meeting 20150218, it was agreed that NDData would be the base data model.
There are still questions about how to actually represent a Spectrum. See issue #4.

**Comment by stscieisenhamer** [comment]
initial definition can be found in stscieisenhamer/specview@b435459de2ea284149c36dac11b90164d1b57486

Will move into appropriate branch/pull request after initial reorg.

**Comment by nmearl** [comment]
This should be solved with f529487b3e0119c6d60d9278d57bc2a176fde995. We should open a new issue if we want to discuss the intricacies of this implementation.
