### ISSUE TITLE
Closing out first sprint

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specview#32]
## Punch list

Items to close out for this sprint
- [ ] Documentation _own issue_
- [ ] Aligning spectra _own issue_
- [ ] Copy region information between layers
- [x] UI integration of equivalent width measurements
- [x] rebase 
## Future thoughts
- Unit testing _own issue_
- Glue integration _own issue_
- In-UI terminal (IPython) _done_
- Saved parameter file for models _own issue_

**Comment by stscieisenhamer** [comment]
It has been a bit of time since the sprint. Will separate these out and will ask whether it is good to close this issue?

**Comment by stscieisenhamer** [comment]
Not sure what 'copy region information between layers' mean?
If an ROI exists, changing layers will cause the ROI to apply to the new layer. Does this mean between plot windows?

**Comment by SaOgaz** [comment]
Closing, repository being archived.
