### ISSUE TITLE
PySide and relative imports

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specview#43]
PyQt and PySide are not interchangeable. They actually contain many differences that a lot of the current functionality is not built for. I've added some hacky try/except blocks around signals, as the implementation is different for each (QtCore.pyqtSignal vs QtCore.Signal). This _will_ be changed, mainly because I **strongly** dislike try/except crutches (off the bat: set QtCore.Signal = QtCore.pyqtSignal when using PyQT). Also: file opening dialogs work differently. See [here](http://wiki.qt.io/Differences_Between_PySide_and_PyQt) for more details.

I strongly recommend _not_ allowing PySide to be used right now, or if it is, give a terminal warning to the user that there may be bugs that we are not keeping a particular eye out for.

Second, be wary of relative imports (see main.py)! Implicit relative imports are strong discouraged.  Relative imports _only_ work from in a module that was imported as part of a package. In the case where main.py is **main**, relative importing will fail.

**Comment by stscieisenhamer** [comment]
With regards to the PySide issue: if you wish to back out all that out feel free, because SSB is good with just PyQt for the initial builds. I had left it in there only because I had not realized there were in-app dependencies yet; it was on the list to check. That should help with try/except issues.  Besides, if PySide is ever included again, the appropriate adapter module would be included.

**Comment by stscieisenhamer** [comment]
And curious about the relative import: was this actually an issue just now? This was supposed to be fixed since 2.6.

**Comment by nmearl** [comment]
Yeah. You can try it by commenting out the try/except portion of `main.py` and running it on the command line. You'll get a `ValueError` complaining about non-packages, which is correct because `main.py` is not being used as a package in that instance.

**Comment by stscieisenhamer** [comment]
ah, sorry, I misunderstood what you were saying.

**Comment by stscieisenhamer** [comment]
Any thoughts on the pyside inclusion? Again, for the moment, this isn't a concern on our end; being PyQt only is OK. No need for unhappy/hacky code if its not necessary. I can do the backout if necessary. However, if you prefer it to stay, that's fine also.

**Comment by SaOgaz** [comment]
Closing, repository being archived.
