### ISSUE TITLE
glue integration

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/specview#69]

**Comment by nmearl** [comment]
This will be a tough one. I can see this needing a few sprints, mainly because we will probably have to do a lot of manipulating of glue code to get it to work well with our data structures.

**Comment by stscieisenhamer** [comment]
Yes, agreed. And it may be that it isn't a direct plugin. However, if we keep this in mind, whatever toolsets are built here could be more easily incorporated into a glue-based spectral viewer. 

A possible path would be to ensure that our viewer, minus the data tree model, being already provided for in glue, is sufficiently modular to become a glue viewer (I think its called a client).

**Comment by SaOgaz** [comment]
Closing, repository being archived.
