### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/specview#7]
Need to determine what gets logged as the user goes through a session with the tool.

**Comment by ibusko** [comment]
Perhaps "every user action that results in a change in either the plot or the data/model being plotted/fitted". By that I mean that these actions should end up in a script-like file that can be later used to play back, resulting in the same state the tool had when the log file was closed .

Thus, an action like zooming perhaps should be recorded, but actions associated to simple exploration, like e.g. clicking on a spectrum to see the metadata, shouldn't be recorded. 

This logging thing has perhaps some overlap with the measurement functionalities. If the user uses for instance the equivalent width tool to examine a spectral line, should the result be recorded in the log file, or in a separate output dedicated to the scientifically meaningful results?

**Comment by hcferguson** [comment]
I don't think zooming and panning need to be recorded. But region selections do.

Probably worth thinking about having all, or nearly all, the information that might be logged also available as class attributes. So, for example, once you have measured an equivalent width and reported it to the log file, you also can retrieve it programmatically as spectrum[id].equivalent_width, or something like that.

**Comment by ibusko** [comment]
Zooming and panning change the view of the data. The idea, I think, is to be able to reproduce whatever is being displayed, so the plot can in principle be recovered by playing back the logging file. Perhaps instead of recording every single zoom/pan action, the log file should record just the last viewport then.

**Comment by hcferguson** [comment]
Being able to print to the log file or on the screen -- on request -- the current bounding box for the plot is useful. Recording every change of state to the log probably clutters up the log file too much.

**Comment by stscieisenhamer** [comment]
From standup 20150219
- How much plot info?
- State information: what has been done with the data?
- Make it a user action

**Comment by stscieisenhamer** [comment]
Relevant issues:
- issue #8
- issue #53

**Comment by SaOgaz** [comment]
Closing, repository being archived.
