### ISSUE TITLE
SpectrumData using NDData separately for x and y value

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/specview#74]
At the moment, it looks like `SpectrumData` uses `NDData` for the x and y axis separately - I noticed this in the following code:

```
        spec_x_array = spec_data.x.convert_unit_to(self._units[0])
        spec_y_array = spec_data.y.convert_unit_to(self._units[1])
```

However, this is not how it was intended to be used - the x axis should be part of the WCS. I think instead that you should be using the `Spectrum1D` class from [specutils](https://github.com/astropy/specutils) (which now has a release) and which inherits from `NDData`.

cc @stscieisenhamer @ibusko @perrygreenfield

**Comment by astrofrog** [comment]
I could look into how to transition and try and open a PR if there is interest in this?

**Comment by SaOgaz** [comment]
Closing, repository being archived.
