### ISSUE TITLE
Implement residuals plot.

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specview#76]
Implement plot of residuals data - model. 

To pre-empt the surely to come requests from users, from the outset make this plot switchable between linear and dex Y mappings.

**Comment by nmearl** [comment]
Technically, this is already a thing. In the current case, you must open the console and subtract the two data sets yourself (this falls under the umbrella of arithmetic functionality that, currently, is on the user to perform).

**Comment by ibusko** [comment]
Right, I know it's possible to do that. What I am targeting is an automatic residuals plot that shows simultaneously as the main plot, whenever a fit is executed,. Without any user intervention or action. In my experience developing other fitting applications, this is the way most users are used to see a fit: a dual plot pane with the main data, and residuals.

**Comment by nmearl** [comment]
Ah, I see. I'll look into this.

**Comment by SaOgaz** [comment]
Closing, repository being archived.
