### ISSUE TITLE
More flexible compound models for fitting.

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specview#77]
Right now, whenever more than one astropy spectral model function is present in the model editor window, the fitting code creates a resulting CompoundModel instance which contains the sum of all functions in the window. However, astropy supports compound models where individual functions can be grouped and combined in arbitrary ways, via a mathematical expression.

We should upgrade the GUI to allow the user to edit such an expression, which will them be passed to the compound model building code.

**Comment by ibusko** [comment]
Internal to an astropy compound model instance, there is an expression like

u'[0] + [1] \* ([2] + [3])' ..... 

in which each function is labelled with a sequential number. This works in the instance, where functions are already frozen inside a sequence. Our problem is more complicated, in which the list of functions kept in the editor window is changeable by the user, by adding, removing, and even moving functions into a different sequential ordering (this is not implemented in specview, but is implemented in the 'modelgui' tool). Thus we need a way to refer to functions in the list from within the expression.

I propose that we label each function instance in the list with a sequential label like 'c01', c'02', ..... _at the time the instance is created_. That way the label will follow the function even when the list gets changed by the user. The expression referes to the functions using the labels and thus doesn't need to be edited when the list gets changed. 

Well, except in one case: when the user deletes a function from the list, the expression is no longer valid until all references to that function are removed, _and_ the function is validated by re-compilation _and_ re-execution. Btw, this issue was never solved in Iris, where a similar expression syntax was used to feed complex spectral models to the Sherpa model fitter.

**Comment by ibusko** [comment]
We should use the 'name' attribute of each function as the placeholder for the label. This would allow parameter ties to be implemented seamlessly.

**Comment by SaOgaz** [comment]
Closing, repository being archived.
